### ISSUE TITLE
Not setting bucket properly?

### ISSUE THREAD

**Issue by marcnicholas** [couchbaselabs/node-ottoman#10]
Running the example (with some setup added) and a known-good bucket seems to throw and object not set error for the bucket?
#### Code

``` javscript
var Ottoman = require('/Users/marc/Code/node-ottoman/lib/ottoman');
var couchbase = require('couchbase');
var uuid = require('node-uuid');

var User = Ottoman.model('User', {
  'username': 'string',
  'name': 'string',
  'email': 'string'
}, {
        test: new couchbase.Connection({})
});

var test = new User();
test.username = 'brett19';
test.name = 'Brett Lawson';
test.email = 'brett19@gmail.com';

Ottoman.save(test, function(err) {
  if (err) throw err;

  MyModel.findById(test._id, function(err, obj) {
    if (err) throw err;

    console.log(obj.name);
    // Brett Lawson
  });
});
```
#### Error

```
/Users/marc/Code/node-ottoman/lib/ottoman.js:476
    obj.$.bucket.set(key, doc, {cas: obj.$cas}, function(){
                 ^
TypeError: Cannot call method 'set' of undefined
    at Object.save (/Users/marc/Code/node-ottoman/lib/ottoman.js:476:18)
    at Object.<anonymous> (/Users/marc/Code/drywall-marc/foo.js:18:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by rajahimanath** [comment]
is the connection closed automatically once the call is done or we have too close the connection explicitly?
