### ISSUE TITLE
The couchbase module version used by the application does not match Ottomans

### ISSUE THREAD

**Issue by Xiad32** [couchbaselabs/node-ottoman#229]
I am receiving the following error:
```
C:\...\node_modules\ottoman\lib\cbstoreadapter.js:33
      throw new Error('The couchbase module version used by the application'
            ^
Error: The couchbase module version used by the application does not match Ottomans.  Please explicitly pass the application couchbase module using `StoreAdapter.Couchbase`.
    at new CbStoreAdapter (C:\...\node_modules\ottoman\lib\cbstoreadapter.js:33:13)
    at Ottoman.set (C:\...\node_modules\ottoman\lib\ottoman.js:55:20)
    at Object.<anonymous> (C:\...\dist\models\planheader.js:11:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (C:\...node_modules\ts-node\src\index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .js] (C:\...\node_modules\ts-node\src\index.ts:839:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\...\dist\server.js:15:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (C:\...\node_modules\ts-node\src\index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .js] (C:\...\node_modules\ts-node\src\index.ts:839:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ...@1.0.0 start: `npm run build && ts-node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jobplannerbackend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Roaming\npm-cache\_logs\2020-05-14T13_55_47_266Z-debug.log
```
Tried searching documentation on which versions of couchbase SDK to use with which version of Ottoman but couldn't find it.

There are versions of the packages I am using:
```
"dependencies": {
    "@types/express": "^4.17.6",
    "@types/node": "^13.11.1",
    "body-parser": "*",
    "couchbase": "^3.0.0",
    "express": "^4.17.1",
    "ottoman": "^1.0.6",
    "ts-node": "^8.8.2"
  },
  "devDependencies": {
    "nodemon": "^2.0.3",
    "tslint": "^6.1.1",
    "typescript": "^3.8.3"
  }
```
The code extract is as follows:
```
const couchbase = require('couchbase');
const ottoman = require('ottoman');

// Server details
const serverHttp = 'http://...';
const authentication = { username: '...', password: '...' }
const bucketName = '...';

// Connect to the server
const cluster = new couchbase.Cluster(serverHttp, authentication);
ottoman.bucket = cluster.bucket(bucketName)
```

**Comment by AV25242** [comment]
Ottoman 1.0.6 is not compatible with Couchbase 3.0.0 upgrade to Ottoman V2
