### ISSUE TITLE
issue after upgrade from 2.0.0-beta.7 to 2.0.0-beta.9

### ISSUE THREAD

**Issue by noiissyboy** [couchbaselabs/node-ottoman#593]
Since upgrade  Iam facing below error on ottoman, using  with couchbase 3.2.2 and serve couchbase community 7.0, any fix would be a geat help, Thanks in advnce 
TypeError: Cannot read property 'collections' of undefined
    at Ottoman.get collectionManager [as collectionManager] (C:\Users\vicky\Projects\API\backend\node_modules\ottoman\src\ottoman\ottoman.ts:120:25)
    at Ottoman.<anonymous> (C:\Users\vicky\Projects\API\backend\node_modules\ottoman\src\ottoman\ottoman.ts:383:18)
    at Generator.next (<anonymous>)
    at C:\Users\vicky\Projects\API\backend\node_modules\ottoman\lib\ottoman\ottoman.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\vicky\Projects\API\backend\node_modules\ottoman\lib\ottoman\ottoman.js:23:12)
    at Ottoman.ensureCollections (C:\Users\vicky\Projects\API\backend\node_modules\ottoman\lib\ottoman\ottoman.js:335:16)
    at Ottoman.<anonymous> (C:\Users\vicky\Projects\API\backend\node_modules\ottoman\src\ottoman\ottoman.ts:432:16)
    at Generator.next (<anonymous>)
    at C:\Users\vicky\Projects\API\backend\node_modules\ottoman\lib\ottoman\ottoman.js:27:71

**Comment by gsi-alejandro** [comment]
hi @noiissyboy 

In the new beta.9 the `connect` function is async.

check the updated docs [here](https://ottomanjs.com/#getting-started)

It's a breaking change from the previous version. sorry about that.

P.S. We are also working in a changelog.md to notify user about what's new and breaking changes if exists.
