### ISSUE TITLE
cannot read property 'collections' of undefined ...

### ISSUE THREAD

**Issue by bwgjoseph** [couchbaselabs/node-ottoman#602]
Hi,

For unknown reason to me, when I startup my application, it will throw me this error

```log
\bwgjoseph\feathers-ottoman-demo>npm run dev

> feathers-ottoman-demo@0.0.0 dev \bwgjoseph\feathers-ottoman-demo
> ts-node-dev --no-notify src/

[INFO] 14:42:43 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.3)
error: start error Cannot read property 'collections' of undefined {"stack":"TypeError: Cannot read property 'collections' of undefined\n    at Ottoman.get collectionManager [as collectionManager] (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\src\\ottoman\\ottoman.ts:158:25)\n    at Ottoman.<anonymous> (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\src\\ottoman\\ottoman.ts:421:18)\n    at Generator.next (<anonymous>)\n    at bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:27:71\n    at new Promise (<anonymous>)\n 
   at __awaiter (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:23:12)\n    at Ottoman.ensureCollections (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:360:16)\n    at Ottoman.<anonymous> (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\src\\ottoman\\ottoman.ts:479:16)\n    at Generator.next (<anonymous>)\n    at bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:27:71"}
(node:28096) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'config' of undefined
    at \bwgjoseph\feathers-ottoman-demo\src\index.ts:20:63
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: connected to ottoman succesfully
```

The second part of the error (regarding config) can be ignored as it should be because of the initial error from `ottoman`.

So for the case above, I am still able to "connect" to `ottoman`, but if I were to restart the application, and it will throw me another exception which would not start at all. It's quite random, and I cannot fully replicate between being able to connect, and throwing the exception while connecting

```log
bwgjoseph\feathers-ottoman-demo>npm run dev

> feathers-ottoman-demo@0.0.0 dev bwgjoseph\feathers-ottoman-demo
> ts-node-dev --no-notify src/

[INFO] 14:46:43 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.3)
error: start error Cannot read property 'collections' of undefined {"stack":"TypeError: Cannot read property 'collections' of undefined\n    at Ottoman.get collectionManager [as collectionManager] (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\src\\ottoman\\ottoman.ts:158:25)\n    at Ottoman.<anonymous> (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\src\\ottoman\\ottoman.ts:421:18)\n    at Generator.next (<anonymous>)\n   
 at bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:27:71\n 
   at new Promise (<anonymous>)\n    at __awaiter (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:23:12)\n    at Ottoman.ensureCollections (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:360:16)\n    at Ottoman.<anonymous> (bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\src\\ottoman\\ottoman.ts:479:16)\n    at Generator.next (<anonymous>)\n    at bwgjoseph\\feathers-ottoman-demo\\node_modules\\ottoman\\lib\\ottoman\\ottoman.js:27:71"}
(node:26772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'config' of undefined
    at bwgjoseph\feathers-ottoman-demo\src\index.ts:20:63
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an 
async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: init error timeout {"cause":{"code":201},"name":"TimeoutError","stack":"TimeoutError: timeout\n    at Object.translateCppError (bwgjoseph\\feathers-ottoman-demo\\node_modules\\couchbase\\dist\\bindingutilities.js:180:20)\n    at Object.<anonymous> (bwgjoseph\\feathers-ottoman-demo\\node_modules\\couchbase\\dist\\connection.js:147:54)"}
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! feathers-ottoman-demo@0.0.0 dev: `ts-node-dev --no-notify src/`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the feathers-ottoman-demo@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2021-10-10T06_46_49_461Z-debug.log
```

Have never seen this error in the previous beta test. Was trying to upgrade it to the 2.0.0 (GA), and got this. My repo is in [here](https://github.com/bwgjoseph/feathers-ottoman-demo/tree/upgrade-feathers-ottoman). Enabling `debug` mode doesn't help since there isn't any log coming out to show any info

Let me know if more info is required

**Comment by brett19** [comment]
Hey @bwgjoseph ,

Can you share a piece of example code that demonstrates this happening?

Cheers, Brett

**Comment by brett19** [comment]
Hey @bwgjoseph,

In hindsight, I just noticed you did in fact include a link to your code.  The main thing I noticed in your code is that your ottoman.ts file initializes a new ottoman instance, rather than the default instance, but the application startup calls `ottoman.start()` which will be based on the default instance.  You should try and make it so your application startup invokes the start() method on the appropriate ottoman instance (and only once `connect` has been invoked).  I suspect your code has a race condition between calling start and the connect completing and there being a connection to run the startup process against.

Cheers, Brett

**Comment by bwgjoseph** [comment]
Hi @brett19,

Thanks for getting back. As far as I understand, and also mentioned in the [docs](https://ottomanjs.com/guides/ottoman.html#default-ottoman-instance), that is the first instance will be the default instance.

I am only initializing a instance in `ottoman.ts`, and then connect it slightly later because `start` only can run after all my `models` has been init as well
