### ISSUE TITLE
Cannot read properties of undefined (reading 'collections')

### ISSUE THREAD

**Issue by bwgjoseph** [couchbaselabs/node-ottoman#629]
Hi,

I encounter the following error while connecting...

```log
C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:173
        return this.bucket.collections();
                           ^

TypeError: Cannot read properties of undefined (reading 'collections')
    at Ottoman.get collectionManager [as collectionManager] (C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:173:28)
    at Ottoman.<anonymous> (C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:375:59)
    at Generator.next (<anonymous>)
    at C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:23:12)
    at Ottoman.ensureCollections (C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:367:16)
    at Ottoman.<anonymous> (C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:444:24)
    at Generator.next (<anonymous>)
    at C:\projects\otto-js\node_modules\ottoman\lib\ottoman\ottoman.js:27:71
```

Using the following script

```js
const {
  Ottoman, getModel, Schema, SearchConsistency,
} = require('ottoman');

const ottoman = new Ottoman({ collectionName: '_default' });

ottoman.connect({
  connectionString: 'couchbase://localhost',
  bucketName: 'testBucket',
  username: 'user',
  password: 'password',
});

const modelOptions = {
  scopeName: 'testpostscope',
  collectionName: 'testpostcollection',
  maxExpiry: 1200,
};

const schema = new Schema({
  text: { type: String },
});

ottoman.model('message', schema, modelOptions);

ottoman.start();

const messageModel = getModel('message');
messageModel.create({ text: 'test' })
  .then((result) => console.log(result));
```

Using `ottoman 2.1.0`. Any idea?

Thanks!

---

Not sure if it helps, here's the log with debug on

```log
❯ node index.js
  couchnode:lcb:info (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:521) Version=3.2.4-njs, Changeset=38cc0708dfcc5a706c6b21dc80bcd84f05890225 +0ms
  couchnode:lcb:info (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:522) Effective connection string: couchbase://localhost?config_total_timeout=30s&enable_tracing=off&enable_operation_metrics=off&client_string=couchnode%2F3.2.4%20(node%2F16.13.2%3B%20v8%2F9.4.146.24-node.14%3B%20ssl%2F1.1.1l%2Bquic). Bucket=(null) +1ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:389) Applying initial cntl config_total_timeout=30s +0ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:389) Applying initial cntl enable_tracing=off +0ms  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:389) Applying initial cntl enable_operation_metrics=off +0ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:389) Applying initial cntl client_string=couchnode/3.2.4 (node/16.13.2; v8/9.4.146.24-node.14; ssl/1.1.1l+quic) +1ms
  couchnode:lcb:info (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:212) DNS SRV lookup failed: LCB_ERR_UNKNOWN_HOST (1049). Ignore this if not relying on DNS SRV records +11ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:155) Adding host localhost:8091 to initial HTTP bootstrap list +10ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:155) Adding host localhost:11210 to initial CCCP bootstrap list +0ms
  couchnode:lcb:trace (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:193) Bootstrap hosts loaded (cccp:1, http:1) +0ms 
  couchnode:lcb:info (bootstrap @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bootstrap.cc:277) Requested network configuration: heuristic +3ms
  couchnode:lcb:debug (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:94) Preparing providers (this may be called multiple times) +2ms
  couchnode:lcb:debug (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:100) Provider CCCP is ENABLED +1ms     
  couchnode:lcb:debug (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:100) Provider HTTP is ENABLED +0ms     
  couchnode:lcb:trace (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:319) Refreshing current cluster map (bucket: (null)) +2ms
  couchnode:lcb:info (cccp @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\bc_cccp.cc:176) Requesting connection to node localhost:11210 for CCCP configuration +2ms
  couchnode:lcb:debug (lcbio_mgr @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\manager.cc:501) <localhost:11210> (HE=00000255A967DA30) Creating new connection because none are available in the pool +1ms
  couchnode:lcb:trace (lcbio_mgr @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\manager.cc:413) <localhost:11210> (HE=00000255A967DA30) New pool entry: I=000002559FA5DB30 +2ms
  couchnode:lcb:info (connection @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\connect.cc:497) <localhost:11210> (SOCK=f4f4a311b8151120) Starting. Timeout=2000000us +1ms
```

**Comment by AV25242** [comment]
Hello @bwgjoseph  hope you are doing good. Thanks for checking 2.1.0 I have reached out to the team and they are investigating

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

try this script which handle some async methods (`connect`, `start`)

```
const {
    Ottoman, getModel, Schema, SearchConsistency,
} = require('ottoman');

const ottoman = new Ottoman({ collectionName: '_default' });

const start = async () => {
    await ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testBucket',
        username: 'user',
        password: 'password',
    });

    const modelOptions = {
        scopeName: 'testpostscope',
        collectionName: 'testpostcollection',
        maxExpiry: 1200,
    };

    const schema = new Schema({
        text: { type: String },
    });

    ottoman.model('message', schema, modelOptions);

    await ottoman.start();

    const messageModel = getModel('message');
    messageModel.create({ text: 'test' })
        .then((result) => console.log(result));
}

start();
```

**Comment by bwgjoseph** [comment]
@AV25242 Thanks for asking, I'm doing well. Hope you are too

@gsi-alejandro thanks for reaching back so soon

Unfortunately, this would work great in such a simple example but I'm facing some issues on an express [feathersjs](https://feathersjs.com/) app.

The flow is like such

```
// connect to ottoman
// initialize services (which in turn initialize the models)
// start the app (which call ottoman.start() first)
```

One of the issues I have is that I can't really await the connection given that the setup is not async so I can't await it

See [ottoman.ts](https://github.com/bwgjoseph/feathers-ottoman-demo/blob/main/src/ottoman.ts) followed by [app.ts](https://github.com/bwgjoseph/feathers-ottoman-demo/blob/main/src/index.ts)

This result in

```
❯ npm run dev

> feathers-ottoman-demo@0.0.0 dev Z:\feathers-ottoman-demo
> ts-node src/index.ts

TypeError: Cannot read properties of undefined (reading 'collections')
    at Ottoman.get collectionManager [as collectionManager] (Z:\feathers-ottoman-demo\node_modules\ottoman\src\ottoman\ottoman.ts:158:25)
    at Ottoman.<anonymous> (Z:\feathers-ottoman-demo\node_modules\ottoman\src\ottoman\ottoman.ts:426:18)
    at Generator.next (<anonymous>)
    at Z:\feathers-ottoman-demo\node_modules\ottoman\lib\ottoman\ottoman.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (Z:\feathers-ottoman-demo\node_modules\ottoman\lib\ottoman\ottoman.js:23:12)
    at Ottoman.ensureCollections (Z:\feathers-ottoman-demo\node_modules\ottoman\lib\ottoman\ottoman.js:367:16)
    at Ottoman.<anonymous> (Z:\feathers-ottoman-demo\node_modules\ottoman\src\ottoman\ottoman.ts:484:16)
    at Generator.next (<anonymous>)
    at Z:\feathers-ottoman-demo\node_modules\ottoman\lib\ottoman\ottoman.js:27:71
info: Feathers application started on http://localhost:3030
info: connected to ottoman succesfully
```

The error was thrown, then the application started, then finally, the connection to the ottoman is initialized and connected.

This may cause an issue where the app is ready before DB is. This may not be an actual concern but want to see if there is any workaround that might help. 

And then another issue is that it might be due to this error, I think, the scope and collections are not being created.

Let see that in the simplified example, after applying your suggestion, it would display scope and collection being created

```js
❯ node index.js
Scope created:  posts
collection created: posts/postc
_Model {
  text: 'test',
  id: 'cdf59213-0b93-4014-a4fc-db62876eacaf',
  _type: 'message'
}
```

Now, with my demo app (and the log above), the scope and collections associated with the models are not being created. This is why when I ran my test and it shows

```log
1) 'comments' service
       "before each" hook for "registered the service":
     ScopeNotFoundError: scope not found
      at Object.translateCppError (node_modules\ottoman\node_modules\couchbase\dist\bindingutilities.js:212:20)
      at Z:\feathers-ottoman-demo\node_modules\ottoman\node_modules\couchbase\dist\connection.js:248:54

  2) 'posts' service
       "before each" hook for "registered the service":
     ScopeNotFoundError: scope not found
      at Object.translateCppError (node_modules\ottoman\node_modules\couchbase\dist\bindingutilities.js:212:20)
      at Z:\feathers-ottoman-demo\node_modules\ottoman\node_modules\couchbase\dist\connection.js:248:54
```

It's not seen in the UI as well

![image](https://user-images.githubusercontent.com/37484538/153633606-6c1aef57-bdce-483d-bc39-2c9aa947146f.png)

The scope and collection are defined as such

```js
const modelOptions: ModelOptions = {
  scopeName: 'commentscope',
  collectionName: 'commentcollection',
};

const modelOptions: ModelOptions = {
  scopeName: 'postscope',
  collectionName: 'postcollection',
};
```

Hope that I described the problem well. I might have gotten something basic wrong, please do let me know if that's the case. 

If you have any suggestions, I will be happy to hear them too

Thanks!

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 
 
The problem is the models aren't registered when the start function is executed.

Workaround:
Modify your models to something like this example from your attachments.model.ts

```js
import { getModel, model, ModelTypes, Schema, ModelOptions } from 'ottoman';
import { Application } from '../declarations';
import baseSchema from './base.schema';

const modelName = 'attachments';
const modelOptions: ModelOptions = {
  scopeName: 'attachmentscope',
  collectionName: 'attachmentcollection',
};

const schema = new Schema({
  filename: {
    type: String,
    required: true,
  },
  data: {
    type: String,
    required: true,
  },
  mimetype: {
    type: String,
    required: true,
  },
  size: {
    type: Number,
    required: true,
  },
}).add(baseSchema);

const AttachmentsModel = model(modelName, schema, modelOptions);

export default function (app: Application): ModelTypes {
  return getModel(modelName) || AttachmentsModel;
}
```
Notice: now we are registering the model when importing the file, previously the model will be registered in execution time.
The `start` function needs information from models to create `scopes`, `collections` and `indexes`.

**Comment by gsi-alejandro** [comment]
@bwgjoseph about connection I recommend the following changes:

ottoman.ts file
```ts ottoman.ts
import { set, Ottoman, SearchConsistency } from 'ottoman';
import { Application } from './declarations';
import logger from './logger';

set('DEBUG', true);
export const ottoman = new Ottoman({ collectionName: '_default', consistency: SearchConsistency.GLOBAL });

export default function (app: Application): void {
  logger.info('connected to ottoman succesfully');
  app.set('ottomanClient', ottoman);
}
````

index.ts file
```ts index.ts
import { ottoman } from './ottoman';
import app from './app';
import logger from './logger';

const main = async() => {
  try {
    await ottoman.connect({
      connectionString: 'couchbase://localhost',
      bucketName: 'testBucket',
      username: 'user',
      password: 'password'
    });

    await ottoman.start();

    const port = app.get('port');
    const server = app.listen(port);

    server.on('listening', () =>
      logger.info('Feathers application started on http://%s:%d', app.get('host'), port)
    );

    process.on('unhandledRejection', (reason, p) =>
      logger.error('Unhandled Rejection at: Promise %s %s', p, reason)
    );
  } catch (err) {
    console.log(err);
  }
};

main();
````

if you have any doubt I'm available to jump in a call or other ways to solve/explain this issues in the less time possible.

**Comment by bwgjoseph** [comment]
Thanks @gsi-alejandro, your suggestion did worked

Not sure if this is a concern, but on the 2nd run, it will log out failure

The first run

```log
❯ npm run dev

> feathers-ottoman-demo@0.0.0 dev Z:\feathers-ottoman-demo
> ts-node src/index.ts

info: connected to ottoman succesfully
Scope created:  postscope
Scope created:  workspacescope
Scope created:  commentscope
Scope created:  userscope
Scope created:  attachmentscope
collection created: workspacescope/workspacecollection
collection created: attachmentscope/attachmentcollection
collection created: userscope/usercollection
collection created: postscope/postcollection
collection created: commentscope/commentcollection
info: Feathers application started on http://localhost:3030
```

On 2nd run

```
❯ npm run dev

> feathers-ottoman-demo@0.0.0 dev Z:\feathers-ottoman-demo
> ts-node src/index.ts

info: connected to ottoman successfully
Failed creating N1QL index Ottomanpostscopeposts
Failed creating N1QL index Ottomanuserscopeusers
Failed creating N1QL index Ottomancommentscopecomments
Failed creating N1QL index Ottomanattachmentscopeattachments
Failed creating N1QL index Ottomanworkspacescopeworkspaces
info: Feathers application started on http://localhost:3030
```

If that is not an issue, my suggestion would be to maybe change the log to `skipping index creation as index already created: <index name>` or something along the line to prevent confusion?

**Comment by bwgjoseph** [comment]
Could I trouble you to expand a little on

> now we are registering the model when importing the file, previously the model will be registered in execution time

My understanding was that the service initialization would have to init the models first, and I did `await start()` at `index.ts`, hence, the `model` should have been ready when `await start()` is called?

**Comment by bwgjoseph** [comment]
I may have spoken too soon, there's still an issue running the test (I ran only a particular test)

`ts-mocha \"test/services/posts.test.ts\" --recursive --exit`

```log
❯ npm run mocha

> feathers-ottoman-demo@0.0.0 mocha Z:\feathers-ottoman-demo
> ts-mocha "test/services/posts.test.ts" --recursive --exit


Error: Model must be provided
    at new OttomanService (Z:\feathers-ottoman\src\index.ts:46:30)
    at new Users (Z:\feathers-ottoman-demo\src\services\users\users.class.ts:8:5)
    at Function.default_1 (Z:\feathers-ottoman-demo\src\services\users\users.service.ts:28:21)
    at Function.configure (Z:\feathers-ottoman-demo\node_modules\@feathersjs\feathers\lib\application.js:59:8)
    at Function.default_1 (Z:\feathers-ottoman-demo\src\services\index.ts:10:7)
    at Function.configure (Z:\feathers-ottoman-demo\node_modules\@feathersjs\feathers\lib\application.js:59:8)
    at Object.<anonymous> (Z:\feathers-ottoman-demo\src\app.ts:47:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (Z:\feathers-ottoman-demo\node_modules\ts-mocha\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (Z:\feathers-ottoman-demo\node_modules\ts-mocha\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (Z:\feathers-ottoman-demo\test\services\posts.test.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (Z:\feathers-ottoman-demo\node_modules\ts-mocha\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (Z:\feathers-ottoman-demo\node_modules\ts-mocha\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (Z:\feathers-ottoman-demo\node_modules\mocha\lib\nodejs\esm-utils.js:56:20)
    at Object.exports.loadFilesAsync (Z:\feathers-ottoman-demo\node_modules\mocha\lib\nodejs\esm-utils.js:88:20)
    at singleRun (Z:\feathers-ottoman-demo\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at Object.exports.handler (Z:\feathers-ottoman-demo\node_modules\mocha\lib\cli\run.js:374:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-ottoman-demo@0.0.0 mocha: `ts-mocha "test/services/posts.test.ts" --recursive --exit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the feathers-ottoman-demo@0.0.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joseph\AppData\Roaming\npm-cache\_logs\2022-02-12T09_51_30_714Z-debug.log
```

This is run after changes made with your suggestion

**Comment by gsi-alejandro** [comment]
> Could I trouble you to expand a little on
> 
> > now we are registering the model when importing the file, previously the model will be registered in execution time
> 
> My understanding was that the service initialization would have to init the models first, and I did `await start()` at `index.ts`, hence, the `model` should have been ready when `await start()` is called?

yes, the `start` function will use models already registered

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

I will check your test setup, in order to realize what is happening. (I'm pretty sure it's a configuration issue)

Don't revert the changes (the app itself is working? the Restfull API I mean.)

**Comment by bwgjoseph** [comment]
Thanks, no rush

> yes, the start function will use models already registered

> now we are registering the model when importing the file, previously the model will be registered in execution time

Yup, and that's why I don't quite get what you meant on registered in execution time, and during import. If you could expand on those, would appreciate it

**Comment by gsi-alejandro** [comment]
this way:
```ts
const AttachmentsModel = model(modelName, schema, modelOptions);

export default function (app: Application): ModelTypes {
  return getModel(modelName) || AttachmentsModel;
}
```
the model will be registered when the file will be imported (attachments.model.ts), the `model` function will be executed when javascript is importing files (when the code starts to be executed - execution time).


in the previous version:
```ts
export default function (app: Application): ModelTypes {
  const modelName = 'attachments';
  const modelOptions: ModelOptions = {
    scopeName: 'attachmentscope',
    collectionName: 'attachmentcollection',
  };

  const schema = new Schema({
    filename: {
      type: String,
      required: true,
    },
    data: {
      type: String,
      required: true,
    },
    mimetype: {
      type: String,
      required: true,
    },
    size: {
      type: Number,
      required: true,
    },
  }).add(baseSchema);

  return getModel(modelName) || model(modelName, schema, modelOptions);
}
```
the model will be not registered until the exported default function will be executed. (feathersjs will execute it to create the service when requested)
 therefore when the `start` function is executed there are no models registered yet, with no models, Ottoman has no information to create scopes, collections, indexes, ...
 
 
 Summarize:
 
imagine a index.js file with this content
 ```js
 console.log('executed');
 ```
 `node index.js` will produce "executed" (our modification achieve this)
 
 instead this other index.js file with content:
  ```js
 function main() {
   console.log('executed');
 }  
 ```
` node index.js` will produce no output. (`console.log` statement never was executed, just from load the files)

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

I was able to run the tests: (yarn mocha, also 1 test works)
<img width="996" alt="image" src="https://user-images.githubusercontent.com/15661442/154900384-fb97b859-72ff-4d65-ba2a-b7456c176d23.png">

Just follow this steps:
1. create a .mocharc.js with this content
```js
'use strict'

module.exports = {
  exit: true,
  bail: true,
  slow: 1000,
  recursive: true,
  file: ['./test/pretest.ts'],
  timeout: 15000
}
```

2. create a file in test/pretest.ts with this content:
```ts
import {getOttomanInstances} from 'ottoman';
import {ottoman} from '../src/ottoman';

before(async() => {
  await ottoman.connect({
      connectionString: 'couchbase://localhost',
      bucketName: 'testBucket',
      username: 'user',
      password: 'password'
   });

  await ottoman.start();
});

after(async ()=> {
  for (const instance of getOttomanInstances()) {
    await instance.close();
  }
});
```

3. update src/ottoman.ts this way:
```ts
import { set, Ottoman, SearchConsistency } from 'ottoman';
import { Application } from './declarations';
import logger from './logger';

set('DEBUG', true);
export const ottoman = new Ottoman({ collectionName: '_default', consistency: SearchConsistency.GLOBAL });

export default function (app: Application): void {
  logger.info('connected to ottoman succesfully');
  app.set('ottomanClient', ottoman);
}
```

whit this changes just run:
- npm run mocha (yarn mocha)
or
- ts-mocha \"test/services/posts.test.ts\"

everything should work as expected

**Comment by bwgjoseph** [comment]
Hi @gsi-alejandro,

Thanks for the tip. 

Deliberately connecting and disconnecting from `ottoman` before and after the test helps but I don't understand why. It was working perfectly with `ottoman 2.0`. So what changed? And why do I have to deliberately do that?

I removed the `after` portion (close instance), and the test still runs and passes without it

---

Must I connect and disconnect on each test, or can I connect once as a global `beforeAll`? I tried it and it works but I'm not sure if that would affect anything

I have a `hooks.ts`

```ts
import { ottoman } from '../../src/ottoman';

export const mochaHooks = {
  beforeAll: [
    async function () {
      await ottoman.connect({
        connectionString: 'couchbase://localhost',
        bucketName: 'testBucket',
        username: 'user',
        password: 'password'
      });

      await ottoman.start();
    }
  ]
};
```

And simply add `--require "test/hooks/hooks.ts"` to the command

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

Nothing regarding Ottoman's setup behavior has changed from the very beginning I really don't know how it could work for version 2.0. (`start `function was added to automatically create scopes, collections, and indexes, replacing for most cases `ensureIndexes`, but it was just added, the requirements could be raised when you switch to using scopes and collections, though)

and yes you can use `beforeAll` to only connect once, the `afterAll` disconnection is not required but strongly recommended to provide graceful shutdown for your tests.
At least for jest it will fail if you don't resolve all pending promises and is good practice to clean everything after running the tests.

I had to check Mocha documentation because I had never used it before, because of it maybe I didn't provide the best solution just some guidance to realize what's going on and how to solve it.

@bwgjoseph if there is nothing else regarding this ticket feel free to close it.

have a good day, happy coding! 🎉

**Comment by bwgjoseph** [comment]
It is indeed a mystery. 

I agree with you on disconnecting and have added it.

And I believe that #602 is the same issue like this, I only realize this recently, and will be closing that as well.

Appreciate your time and help in troubleshooting this issue with me
