### ISSUE TITLE
v2.2.2 create error 

### ISSUE THREAD

**Issue by RahulChand028** [couchbaselabs/node-ottoman#684]
TimeoutError: timeout
at translateCppError (/home/aubergine/workspace/auth/node_modules/couchbase/dist/bindingutilities.js:184:20)
at /home/aubergine/workspace/auth/node_modules/couchbase/dist/connection.js:248:76 {
cause: LibcouchbaseError: libcouchbase error 201
at translateCppError (/home/aubergine/workspace/auth/node_modules/couchbase/dist/bindingutilities.js:178:21)
at /home/aubergine/workspace/auth/node_modules/couchbase/dist/connection.js:248:76 {
code: 201
},
context: KeyValueErrorContext {
status_code: 4,
opaque: 2,
cas: CbCas { ‘0’: <Buffer 00 00 00 00 00 00 00 00> },
key: ‘Admins::0c96eccf-a58d-4266-b2a2-85fbdb61d031’,
bucket: ‘KartStash’,
collection: ‘admins’,
scope: ‘users’,
context: ‘’,
ref: ‘’
}
}

getting this error while creating document node version is 16.16.0 and ottoman version is 2.2.2 and using capella

but working fine with v2.1.0

**Comment by gsi-alejandro** [comment]
hi @RahulChand028 

Can you provide the schema, model, and create the statement you are using in order to reproduce this issue?

**Comment by AV25242** [comment]
One suggestion @RahulChand028 
Do you have the scopes and collection already created or do you expect Ottoman to create them? I am asking this because there could be a lag in creation of scopes and collections if you want it to be created during `start`. Did you try (just as an experiment) create scope and collections manually first and then start your application. See if you still get the error.

**Comment by RahulChand028** [comment]
Scope and collection are already created. I am just trying to connect with capella.
