### ISSUE TITLE
Ensure Indices throwing errror

### ISSUE THREAD

**Issue by samparsky** [couchbaselabs/node-ottoman#69]
/var/www/nodejs/glass/node_modules/couchbase/lib/bucket.js:746
    throw new TypeError(
    ^

TypeError: First argument needs to be a ViewQuery, SpatialQuery or N1qlQuery.
    at Bucket.query (/var/www/nodejs/glass/node_modules/couchbase/lib/bucket.js:746:11)
    at CbStoreAdapter._ensureGsiIndices (/var/www/nodejs/glass/node_modules/ottoman/lib/cbstoreadapter.js:401:17)
    at /var/www/nodejs/glass/node_modules/ottoman/lib/cbstoreadapter.js:424:10
    at handler (/var/www/nodejs/glass/node_modules/ottoman/lib/cbstoreadapter.js:285:7)
    at /var/www/nodejs/glass/node_modules/couchbase/lib/bucketmgr.js:150:7
    at IncomingMessage.<anonymous> (/var/www/nodejs/glass/node_modules/couchbase/lib/bucketmgr.js:11:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:442:9)

**Comment by Voyz** [comment]
I encountered the same issue. 

Commenting out
`ottoman.ensureIndices(function(){})`
fixes the issue.

Passing empty object {} as options when creating model doesn't seem to help.

**Comment by Voyz** [comment]
Fixed it by removing all node_modules and redoing `npm install --save`. Strangely, it reinstalled same modules with same versions, and now it works.
